# Generated by Django 4.2.4 on 2023-11-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recomendada', models.IntegerField(default=0)),
                ('cantidad_devuelta', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.recomendacion')),
            ],
        ),
    ]
